name: advanced-lane-finding
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - opencv3
    - ffmpeg
    - pip:
        - moviepy
